services:
  # Backend (Elysia)
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: physical-computing-backend
    restart: unless-stopped
    environment:
      # Use external PostgreSQL (from host or remote server)
      DATABASE_URL: ${DATABASE_URL}
      PORT: 3001
      NODE_ENV: production
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend (Next.js)
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: physical-computing-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3001}
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL:-http://localhost:3000}
    depends_on:
      - backend
    ports:
      - "3000:3000"
